unique_ids:
  forms:
    WalletConnect: '1665625918551689688917289.2748'
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: BKW4Q7T5ELLRQGDBC2VMNHAX2B7H5U7R
    theme.css: 4OAPMBFZ4WORLTR2GSWNOHFOLMZF7O4K
  scripts: {}
